language: go
go:
  - "1.11"

install: skip

jobs:
  include:
    - &deploy-stage
      stage: build and deploy
      sudo: required
      script:
        # build
        - >
          docker build -t tfnsw:$DOCKER_TAG         \
            --build-arg CC=$CC                        \
            --build-arg CC_PKG=$CC_PKG                \
            --build-arg CC_GOARCH=$CC_GOARCH          \
            --build-arg VERSION=$TRAVIS_BRANCH        \
            --build-arg BUILD_ARCH=$BUILD_ARCH        \
            --build-arg GIT_COMMIT=$TRAVIS_COMMIT     \
            --build-arg BUILD_TIMESTAMP=$(date +%s)   \
            .
      after_success:
        - |
          echo ${DOCKER_PASSWORD} | docker login --username "rycus86" --password-stdin
          if [ "$TRAVIS_BRANCH" == "master" ]; then
              docker tag tfnsw:${DOCKER_TAG} rycus86/tfnsw-server:${DOCKER_TAG}
              docker push rycus86/tfnsw-server:${DOCKER_TAG}
          else
              docker tag tfnsw:${DOCKER_TAG} rycus86/tfnsw-server:${TRAVIS_BRANCH}-${DOCKER_TAG}
              docker push rycus86/tfnsw-server:${TRAVIS_BRANCH}-${DOCKER_TAG}
          fi
      env:
        - DOCKER_TAG=amd64
        - BUILD_ARCH=amd64

    - <<: *deploy-stage
      env:
        - DOCKER_TAG=armhf
        - BUILD_ARCH=arm32v6
        - CC=arm-linux-gnueabihf-gcc
        - CC_PKG=gccgo-arm-linux-gnueabihf
        - CC_GOARCH=arm

    - <<: *deploy-stage
      env:
        - DOCKER_TAG=aarch64
        - BUILD_ARCH=arm64v8
        - CC=aarch64-linux-gnu-gcc
        - CC_PKG=gccgo-aarch64-linux-gnu
        - CC_GOARCH=arm64

    - stage: manifest
      sudo: required
      script:
        - |
          if [ "$TRAVIS_BRANCH" != "master" ]; then
              sed -i "s#rycus86/tfnsw-server:#rycus86/tfnsw-server:${TRAVIS_BRANCH}-#" manifest.yml
              sed -i "s#rycus86/tfnsw-server:${TRAVIS_BRANCH}-latest#rycus86/tfnsw-server:${TRAVIS_BRANCH}#" manifest.yml
          fi
        - echo ${DOCKER_PASSWORD} | docker login --username "rycus86" --password-stdin
        - curl -fsSL https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 > ./manifest-tool
        - chmod +x ./manifest-tool
        - ./manifest-tool push from-spec manifest.yml

